refactor: remove `onChangedNullable`, update `onChanged` for null val…
nank1ro/flutter-shadcn-ui pull request #177
Opened 2024-10-26 16:56 UTC by moshOntong-IT

…ues, and set `allowDeselection` default to false

This commit introduces breaking changes:

1. Removed the `onChangedNullable` method to simplify the API and avoid developer confusion. The `onChanged` method now supports returning or callback with a null value. Developers must implement null checks in their code to handle nullable results from `onChanged`.

2. The `allowDeselection` property now defaults to `false`. Ensure your code explicitly sets this to `true` if deselection is needed.

Please update your code to accommodate these changes.

2024-10-26 19:33 UTC, nank1ro requested changes

2024-10-26 19:33 UTC, nank1ro commented on example/lib/pages/select_form_field.dart
> +                  // onChanged: allowDeselection ? null : print,
Remove the comments

2024-10-26 19:33 UTC, nank1ro commented on lib/src/components/form/fields/select.dart
> +              // onChangedNullable: onChangedNullable != null
Remove comments

2024-10-26 19:33 UTC, nank1ro commented on lib/src/components/form/fields/select.dart
> +    // /// {@macro ShadSelect.onChangedNullable}
Remove comments

2024-10-26 19:33 UTC, nank1ro commented on lib/src/components/form/fields/select.dart
> +              //     : null,
Remove comments

2024-10-27 00:36 UTC, moshOntong-IT commented on example/lib/pages/select_form_field.dart
> +                  // onChanged: allowDeselection ? null : print,
done

2024-10-27 00:36 UTC, moshOntong-IT commented on lib/src/components/form/fields/select.dart
> +              // onChangedNullable: onChangedNullable != null
done

2024-10-27 00:36 UTC, moshOntong-IT commented on lib/src/components/form/fields/select.dart
> +    // /// {@macro ShadSelect.onChangedNullable}
done

2024-10-27 00:44 UTC, moshOntong-IT commented on lib/src/components/form/fields/select.dart
> +              //     : null,
Done

2024-10-27 00:45 UTC, moshOntong-IT commented
I set the `allowDeselection` into true as a default when the variant type of Select is multiple

2024-10-27 07:20 UTC, nank1ro approved these changes
LGTM

2024-10-27 09:26 UTC, merged